# Generated by Django 2.2.12 on 2020-04-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_l', models.CharField(max_length=10, verbose_name='大業態コード')),
                ('name', models.CharField(max_length=30, verbose_name='カテゴリー名')),
            ],
        ),
        migrations.CreateModel(
            name='Pref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref', models.CharField(max_length=6, verbose_name='都道府県コード')),
                ('name', models.CharField(max_length=10, verbose_name='都道府県名')),
            ],
        ),
    ]
